
#dev_addr: '10.142.0.2:80'
#dev_addr: '0.0.0.0:80'
site_url: 'http://mscurriculum.thinkdataed.org'
plugins:
   - search
#plugins:
#  - pdf-export:
#        verbose: true

site_name: Data Detectives
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - meta
  - attr_list
  - abbr
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji 
      #emoji_generator: !!python/name:materialx.emoji.to_svg
      #:material-video:{title="Video clip"}
      #:material-chat-outline:{title="Discussion"}
      #:material-checkbox-outline:{title="Assessments"}
      #:fontawesome-regular-pen-to-square:{title="Class Scribes"}
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      
theme:
    name: material
    features:
        tabs = true 
        - content.tooltips
extra_javascript:
    - src/sweetalert2/sweetalert2.all.min.js
    - src/extra.js
extra_css:
    - src/extra.css

nav:
    - Home: index.md
    - Table of Contents: table.md
    - Overview & Philosophy: overview.md
    - Scope and Sequence: scope.md
    - Unit1:
        - Table of Contents: unit1/overview.md
        - 'Section 1': 
            - 'Setting the Stage':    unit1/section1.md
            - 'Lesson 1: Meet the DSU Squad (DSU = Data Science Unit)' : unit1/lesson1.md
            - 'Lesson 2: Reconstructing the Scene' : unit1/lesson2.md
            - 'Lesson 3: Compiling the Suspect Dossiers' : unit1/lesson3.md
            - 'Lesson 4: Acquiring & Organizing Additional Evidence' : unit1/lesson4.md
            - 'Lesson 5: Structuring the Evidence' : unit1/lesson5.md
            - 'Lesson 6: Our Detective Toolkit - CODAP' : unit1/lesson6.md
            - 'Lesson 7: What’s in a Question?' : unit1/lesson7.md
            - 'Progress Check 1: Can You Read the Evidence?' : unit1/progresscheck1.md
        - 'Section 2': 
            - 'Plotting the Clues':    unit1/section2.md
            - 'Lesson 8: Spot the Plot' : unit1/lesson8.md
            - 'Lesson 9: Placing Categorical Evidence Behind Bars' : unit1/lesson9.md
            - 'Lesson 10: Connecting the Dots' : unit1/lesson10.md
            - 'Lesson 11: The Plot Thickens' : unit1/lesson11.md
            - 'Lesson 12: The Shape of Data' : unit1/lesson12.md
            - 'Progress Check 2: Can You Analyze Evidence?' : unit1/progresscheck2.md
        - 'Section 3':
            - 'Wrapping Up the Case':    unit1/section3.md
            - 'Lesson 13: The Average Suspect' : unit1/lesson13.md
            - 'Lesson 14: Getting MAD About It' : unit1/lesson14.md
            - 'Lesson 15: When the Mean is Unfair - Introducing the Median' : unit1/lesson15.md
            - 'Lesson 16: Boxing Up the Evidence' : unit1/lesson16.md
            - 'Lesson 17: Choosing the Right Tools for Center and Spread' : unit1/lesson17.md
            - 'Progress Check 3: Can You Interpret Evidence' : unit1/progresscheck3.md
            - 'Additional Assessment: Your Turn, Detective! A Full Data Cycle Investigation' : unit1/assess1.md
            - 'Unit 1 Final Mission: The Data Detective’s Case Report' : unit1/end.md
    #- Unit2:
        #- Daily Overview: unit2/overview.md
        #- 'Section 1': 
            #- 'What is Your True Color?':    unit2/section1.md
            #- 'Lesson 1: What is Your True Color?' : unit2/lesson1.md
            #- 'Lesson 2: What Does Mean Mean?' : unit2/lesson2.md
            #- 'Lesson 3: Median in the Middle' : unit2/lesson3.md
            #- 'Lesson 4: How Far is it from Typical?' : unit2/lesson4.md
            #- 'Lab 2A - All About Distributions' : unit2/lab2a.md
            #- 'Lesson 5: Human Boxplots' : unit2/lesson5.md
            #- 'Lesson 6: Face Off' : unit2/lesson6.md
            #- 'Lesson 7: Plot Match' : unit2/lesson7.md
            #- 'Lab 2B - Oh the Summaries ...' : unit2/lab2b.md
            #- 'Practicum: The Summaries' : unit2/practicum1.md
        #- 'Section 2': 
            #- 'How Likely is it?':    unit2/section2.md
            #- 'Lesson 8: How Likely Is It?' : unit2/lesson8.md
            #- 'Lesson 9: Dice Detective' : unit2/lesson9.md
            #- 'Lesson 10: Marbles, Marbles…' : unit2/lesson10.md
            #- 'Lab 2C - Which Song Plays Next?' : unit2/lab2c.md
            #- 'Lesson 11: This AND/OR That' : unit2/lesson11.md
            #- 'Lab 2D - Queue It Up!' : unit2/lab2d.md
            #- 'Practicum: Win, Win, Win' : unit2/practicum2.md
       # - 'Section 3':
           # - 'What Are the Chances That You Are Stressing or Chilling?':    unit2/section3.md  
            #- 'Lesson 12: Don’t Take My Stress Away!' : unit2/lesson12.md
            #- 'Campaign Guidelines – Stress/Chill' : unit2/campaign1.md
            #- 'Lesson 13: The Horror Movie Shuffle' : unit2/lesson13.md
            #- 'Lab 2E - The Horror Movie Shuffle' : unit2/lab2e.md
            #- 'Lesson 14: The Titanic Shuffle' : unit2/lesson14.md
            #- 'Lab 2F - The Titanic Shuffle' : unit2/lab2f.md
            #- 'Lesson 15: Tangible Data Merging' : unit2/lesson15.md
            #- 'Lab 2G - Getting It Together' : unit2/lab2g.md
            #- 'Practicum: What Stresses Us?' : unit2/practicum3.md
        #- 'Section 4':  
            #- 'What’s Normal?':    unit2/section4.md  
            #- 'Lesson 16: What Is Normal?' : unit2/lesson16.md
            #- 'Lesson 17: A Normal Measure of Spread' : unit2/lesson17.md
            #- 'Lesson 18: What’s Your Z-Score?' : unit2/lesson18.md
            #- 'Lab 2H - Eyeballing Normal' : unit2/lab2h.md
            #- 'Lab 2I - R’s Normal Distribution Alphabet' : unit2/lab2i.md
            #- 'End of Unit 2 Project: Comparing Groups Using Our Own Data' : unit2/end.md
    #- Unit3:
        #- 'Daily Overview' : unit3/overview.md
        #- 'Section 1': 
            #- 'Testing, Testing…1, 2, 3…' : unit3/section1.md
            #- 'Lesson 1: Anecdotes vs. Data' : unit3/lesson1.md
            #- 'Lesson 2: What Is an Experiment?' : unit3/lesson2.md
            #- 'Lesson 3: Let’s Try an Experiment!' : unit3/lesson3.md
            #- 'Lesson 4: Predictions, Predictions' : unit3/lesson4.md
            #- 'Lesson 5: Time Perception Experiment' : unit3/lesson5.md
            #- 'Lab 3A: The Results Are In!' : unit3/lab3a.md
            #- 'Practicum: TB or Not TB' : unit3/practicum1.md  
        #- 'Section 2': 
            #- 'Would You Look at That?' : unit3/section2.md
            #- 'Lesson 6: Observational Studies' : unit3/lesson6.md
            #- 'Lesson 7: Observational Studies vs. Experiments' : unit3/lesson7.md
            #- 'Lesson 8: Monsters That Hide in Observational Studies' : unit3/lesson8.md
            #- 'Lab 3B: Confound It All!' : unit3/lab3b.md
        #- 'Section 3': 
            #- 'Are You Asking Me?' : unit3/section3.md
            #- 'Lesson 9: Survey Says…' : unit3/lesson9.md
            #- 'Lesson 10: We’re So Random' : unit3/lesson10.md
            #- 'Lesson 11: The Gettysburg Address' : unit3/lesson11.md
            #- 'Lab 3C: Random Sampling' : unit3/lab3c.md
            #- 'Lesson 12: Bias in Survey Sampling' : unit3/lesson12.md
            #- 'Lesson 13: The Confidence Game' : unit3/lesson13.md
            #- 'Lesson 14: How Confident Are You?' : unit3/lesson14.md
            #- 'Lab 3D: Are You Sure about That?' : unit3/lab3d.md
            #- 'Practicum: Let’s Build a Survey!' : unit3/practicum2.md  

    - Vocabulary: 
        - 'Unit 1 Vocabulary' : vocabulary/unit1.md
        #- 'Unit 2 Vocabulary' : vocabulary/unit2.md
        #- 'Unit 3 Vocabulary' : vocabulary/unit3.md

    - PDF: 
       #- 'IDS_Curriculum' : download/curriculum.md
        - 'MSDS_LMRs' : download/lmrs.md
        #- 'MSDS_Lab Response Sheets' : download/labs.md
        #- 'MSDS_Teacher Resources' : download/resources.md
    
    #- AppDownloads: download/app.md
    
    - How to..Video:  video.md

    - Applications: applications.md    

    - Extra Datasets: data.md    
   
    - Updates: updates.md

google_analytics: ['UA-149684808-1', 'curriculum.thinkdataed.org']

gtag:
  - G-K2MVBFZP2D

extra:
  analytics:
    provider: google
    property: G-K2MVBFZP2D
    property: UA-149684808-1

#plugins:
#    - search:
#        lang: en
#        separator: '[\s\-]+'
#dev_addr: '192.168.0.9:80'
