
#dev_addr: '10.142.0.2:80'
#dev_addr: '0.0.0.0:80'
site_url: 'http://mscurriculum.thinkdataed.org'
plugins:
   - search
#plugins:
#  - pdf-export:
#        verbose: true

site_name: Data Detectives
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - meta
  - attr_list
  - abbr
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji 
      #emoji_generator: !!python/name:materialx.emoji.to_svg
      #:material-video:{title="Video clip"}
      #:material-chat-outline:{title="Discussion"}
      #:material-checkbox-outline:{title="Assessments"}
      #:fontawesome-regular-pen-to-square:{title="Class Scribes"}
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      
theme:
    name: material
    features:
        tabs = true 
        - content.tooltips
extra_javascript:
    - src/sweetalert2/sweetalert2.all.min.js
    - src/extra.js
extra_css:
    - src/extra.css

nav:
    - Home: index.md
    - Unit1:
        - Table of Contents: unit1/overview.md
        - 'Section 1': 
            - 'Setting the Stage':    unit1/section1.md
            - 'Lesson 1: Meet the DSU Squad (DSU = Data Science Unit)' : unit1/lesson1.md
            - 'Lesson 2: Reconstructing the Scene' : unit1/lesson2.md
            - 'Lesson 3: Compiling the Suspect Dossiers' : unit1/lesson3.md
            - 'Lesson 4: Acquiring & Organizing Additional Evidence' : unit1/lesson4.md
            - 'Lesson 5: Structuring the Evidence' : unit1/lesson5.md
            - 'Lesson 6: Our Detective Toolkit - CODAP' : unit1/lesson6.md
            - 'Lesson 7: What’s in a Question?' : unit1/lesson7.md
            - 'Progress Check 1: Can You Read the Evidence?' : unit1/progresscheck1.md
        - 'Section 2': 
            - 'Plotting the Clues':    unit1/section2.md
            - 'Lesson 8: Spot the Plot' : unit1/lesson8.md
            - 'Lesson 9: Placing Categorical Evidence Behind Bars' : unit1/lesson9.md
            - 'Lesson 10: Connecting the Dots' : unit1/lesson10.md
            - 'Lesson 11: The Plot Thickens' : unit1/lesson11.md
            - 'Lesson 12: The Shape of Data' : unit1/lesson12.md
            - 'Progress Check 2: Can You Analyze Evidence?' : unit1/progresscheck2.md
        - 'Section 3':
            - 'Wrapping Up the Case':    unit1/section3.md
            - 'Lesson 13: The Average Suspect' : unit1/lesson13.md
            - 'Lesson 14: Getting MAD About It' : unit1/lesson14.md
            - 'Lesson 15: When the Mean is Unfair - Introducing the Median' : unit1/lesson15.md
            - 'Lesson 16: Boxing Up the Evidence' : unit1/lesson16.md
            - 'Lesson 17: Choosing the Right Tools for Center and Spread' : unit1/lesson17.md
            - 'Progress Check 3: Can You Interpret Evidence' : unit1/progresscheck3.md
            - 'Additional Assessment: Your Turn, Detective! A Full Data Cycle Investigation' : unit1/assess1.md
            - 'Unit 1 Final Mission: The Data Detective’s Case Report' : unit1/end.md
    #- Unit2:
        #- Daily Overview: unit2/overview.md
        #- 'Section 1': 
            #- 'Section Name':    unit2/section1.md
            #- 'Lesson 1: Compair-a-Chutes' : unit2/lesson1.md
            #- 'Lesson 2: Construct-a-Chute' : unit2/lesson2.md
            #- 'Lesson 3: Compare-a-Chutes' : unit2/lesson3.md
            #- 'Lesson 4: The Board Meeting' : unit2/lesson4.md
            #- 'Progress Check 1: ' : unit2/progresscheck1.md
        #- 'Section 2': 
            #- 'Section Name':    unit2/section2.md
            #- 'Lesson 5: Reaching Higher' : unit2/lesson5.md
            #- 'Lesson 6: Two Measurements One Story' : unit2/lesson6.md
            #- 'Lesson 7: Describing Patterns in Scatterplots' : unit2/lesson7.md
            #- 'Lesson 8: Warning Signs' : unit2/lesson8.md
            #- 'Lesson 9: The Point of No Return' : unit2/lesson9.md
            #- 'Lesson 10: Off the Charts' : unit2/lesson10.md
            #- 'Progress Check 2: ' : unit2/progresscheck2.md
       # - 'Section 3':
           # - 'Section Name':    unit2/section3.md  
            #- 'Lesson 11: The Average Bear' : unit2/lesson11.md
            #- 'Lesson 12: Just the Facts' : unit2/lesson12.md
            #- 'Lesson 13: Fact Check' : unit2/lesson13.md
            #- 'Lesson 14: How Are the Categories Spread Out?' : unit2/lesson14.md
            #- 'Lesson 15: Two Variables at Once' : unit2/lesson15.md
            #- 'Lesson 16: Percents Tell the Story' : unit2/lesson16.md
            #- 'Lesson 17: From Hand to Tool' : unit2/lesson17.md
            #- 'Lesson 18: Does the Data Tell a Story?' : unit2/lesson18.md
            #- 'Progress Check 3: ' : unit2/progresscheck3.md
            #- 'Additional Assessment:' : unit2/assess1.md
            #- 'Unit 2 Final Mission' : unit2/end.md

    #- Unit3:
        #- 'Daily Overview' : unit3/overview.md
        #- 'Section 1': 
            #- 'Section Name' : unit3/section1.md
            #- 'Lesson 1: ' : unit3/lesson1.md
            #- 'Lesson 2: ' : unit3/lesson2.md
            #- 'Lesson 3: ' : unit3/lesson3.md
            #- 'Lesson 4: ' : unit3/lesson4.md
            #- 'Lesson 5: ' : unit3/lesson5.md
            #- 'Progress Check 1:' : unit3/progresscheck1.md  
        #- 'Section 2': 
            #- 'Section Name' : unit3/section2.md
            #- 'Lesson 6: ' : unit3/lesson6.md
            #- 'Lesson 7: ' : unit3/lesson7.md
            #- 'Lesson 8: ' : unit3/lesson8.md
            #- 'Lesson 9: ' : unit3/lesson9.md
            #- 'Lesson 10: ' : unit3/lesson10.md
            #- 'Lesson 11: ' : unit3/lesson11.md
            #- 'Lesson 12: ' : unit3/lesson12.md
            #- 'Progress Check 2:' : unit3/progresscheck2.md
        #- 'Section 3': 
            #- 'Section Name' : unit3/section3.md
            #- 'Lesson 13: ' : unit3/lesson13.md
            #- 'Lesson 14: ' : unit3/lesson14.md
            #- 'Lesson 15: ' : unit3/lesson15.md
            #- 'Lesson 16: ' : unit3/lesson16.md
            #- 'Lesson 17: ' : unit3/lesson17.md
            #- 'Lesson 18:' : unit3/lesson18.md
            #- 'Progress Check 3:' : unit3/progresscheck3.md
            #- 'Additional Assessment:' : unit3/assess1.md
            #- 'Unit 3 Final Mission' : unit3/end.md

    - Vocabulary: 
        - 'Unit 1 Vocabulary' : vocabulary/unit1.md
        #- 'Unit 2 Vocabulary' : vocabulary/unit2.md
        #- 'Unit 3 Vocabulary' : vocabulary/unit3.md

    - PDF: 
       #- 'IDS_Curriculum' : download/curriculum.md
        - 'MSDS_LMRs' : download/lmrs.md
        - 'MSDS_Data_Files' : download/dataFiles.md
           
    - References: references.md 

    - Instructional Strategies: instruct_strat.md

google_analytics: ['UA-149684808-1', 'curriculum.thinkdataed.org']

gtag:
  - G-K2MVBFZP2D

extra:
  analytics:
    provider: google
    property: G-K2MVBFZP2D
    property: UA-149684808-1

#plugins:
#    - search:
#        lang: en
#        separator: '[\s\-]+'
#dev_addr: '192.168.0.9:80'
